### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by utopieselective** [GER-Space/KOS-Biome#1]
Just found your addon for KOS,
looks great that's exactly what I need.
how do I install it tho?

thanks!

**Comment by GER-Space** [comment]
Oh new user :-)

I'll update it to the latest releases of KSP and kOS. After that you unpack te zip to the gamedata folder.

**Comment by GER-Space** [comment]
Get the release here:
https://github.com/GER-Space/KOS-Biome/releases/tag/1.0.0.1
